---
- name: Restart sshd
  become: 'True'
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart auditd
  become: 'yes'
  ansible.builtin.command: systemctl restart auditd
  args:
    warn: false

- name: Generate auditd
  become: 'yes'
  ansible.builtin.command: augenrules
