---
all:
  children:
    arvan:
      hosts:
        babasholepaz:
          ansible_host: 188.121.105.53
          ansible_port: 8090
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/ali_rsa

    lab:
      hosts:
        lab74:
          ansible_host: vm.lab.canme.ir
          ansible_port: 7174
          ansible_user: st74
          ansible_ssh_private_key_file: ~/.ssh/lab


